name: wavelength_app
description: "Wavelength Premium Music Player"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1+11
  audio_session: ^0.1.16
  youtube_explode_dart: ^2.2.0   # Added for independent background downloading without Next.js!
  dio: ^5.4.0                    # Robust HTTP client for large file downloads
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
